name: Deploy to WordPress.org
on:
  push:
    tags:
    - 'v*'
    - '!v*-alpha*'
    - '!v*-beta*'
jobs:
  tag:
    name: New tag
    runs-on: ubuntu-latest
    steps:
    - uses: dcodeIO/setup-node-nvm@master
      with:
        node-version: 8.16
    - uses: actions/checkout@master
    - name: Build
      run: | 
        npm install
        npm run build
